# Generated by Django 4.2.8 on 2023-12-28 12:42

import admin.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", admin.models.ModelUser()),
            ],
        ),
        migrations.RemoveField(
            model_name="user",
            name="city",
        ),
        migrations.RemoveField(
            model_name="user",
            name="contact_number",
        ),
        migrations.RemoveField(
            model_name="user",
            name="state",
        ),
        migrations.AddField(
            model_name="user",
            name="gender",
            field=models.CharField(
                choices=[("male", "Male"), ("female", "Female")],
                default="unknown",
                max_length=10,
            ),
        ),
    ]
