# Generated by Django 5.0 on 2024-01-23 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0004_hostel_meal_room_roomchange'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=200)),
                ('notice', models.CharField(max_length=1000, null=True)),
            ],
        ),
    ]
